name: Greetings

on:
  pull_request:

jobs:
  greetings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: 'Thank you for making a pull request. We always strive to make the code better, so thank you for contributing.'
