name: Create issues from TODOs

on:
  push:

jobs:
  todo:

    runs-on: ubuntu-latest
    
    steps:
    - name: Getting files from GitHub
      uses: actions/checkout@v1
    - name: todo-actions
      uses: dtinth/todo-actions@v0.2.0


