name: Ruby

on:
  pull_request:
  push:

jobs:
  rubocop_check:
    runs-on: ubuntu-latest
    steps:
    - name: Getting files from GitHub
      uses: actions/checkout@v1
    - name: Rubocop Linter
      uses: andrewmcodes/rubocop-linter-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  testing:
    needs: 
      - rubocop_check
  
    runs-on: ubuntu-latest
    steps:
    - name: Getting files from GitHub
      uses: actions/checkout@v1
    - name: Configuring Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Checking Ruby version
      run: |
        ruby -v
    - name: Build and test with Rake
      env:
        API_KEY_RESEPLANERARE: ${{ secrets.API_KEY_RESEPLANERARE }}
        API_KEY_STOLPTIDSTABELLER: ${{ secrets.API_KEY_STOLPTIDSTABELLER }}
      run: |
        sudo apt-get install libsqlite3-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        gem install rspec
        rake test
