name: Ruby

on:
  pull_request:
  push:

jobs:
  rubocop_check:
    steps:
    - name: Rubocop checks
      uses: gimenete/rubocop-action@1.0
    
  testing:
    need: 
      - rubocop_check
  
    runs-on: ubuntu-latest
    steps:
    - name: Getting files from GitHub
      uses: actions/checkout@v1
    - name: Configuring Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Checking Ruby version
      run: |
        ruby -v
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        rake test
